apiVersion: v1
kind: Service
metadata:
  name: mirs-ui
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mirs-ui