apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mirs-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.mirs.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mirs-ui
            port:
              number: 80
  - host: image.mirs.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mirs-ui
            port:
              number: 80
  - host: pgadmin.mirs.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mirs-pgadmin
            port:
              number: 80