apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirs-postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi