apiVersion: v1
kind: Service
metadata:
  name: mirs-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: mirs-postgres