apiVersion: v1
kind: Service
metadata:
  name: mirs-pgadmin
  namespace: {{ .Values.namespace }}
  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mirs-pgadmin