apiVersion: v1
kind: ConfigMap
metadata:
  name: mirs-kafka-config
  namespace: {{ .Values.namespace }}
  labels:
    app: mirs-kafka
data:
  KAFKA_CFG_NODE_ID: 0
  KAFKA_CFG_PROCESS_ROLES: controller,broker
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka.mirs.svc.cluster.local:9093, 1@kafka.mirs.svc.cluster.local:9093, 2@kafka.mirs.svc.cluster.local:9093
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER