apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirs-kafka-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi