apiVersion: v1
kind: Service
metadata:
  name: mirs-kafka
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: kafka-int
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: kakfa-controller
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: mirs-kafka